---


- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: commandcentral
  tags:
    - sysprep

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: commandcentral
  tags:
    - sysprep

- hosts: commandcentral
  tasks:
    - name: Root tasks
      block:
        - import_role: 
            name: prepare-cce-provisoning
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_file: /etc/ssh/ssh_known_hosts
      become: true
      tags:
        - sysprep
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - name: set facts
          set_fact:
            install_cce: false
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_file: default
          tags:
            - sysprep
        - import_role: 
            name: install-cce
          tags:
            - install
        - import_role: 
            name: configure-cce
          vars:
            config_item: tuning
          tags:
            - configure
        - import_role: 
            name: configure-cce
          vars:
            config_item: creds
          tags:
            - configure
        - import_role: 
            name: configure-cce
          vars:
            config_item: licenses
          tags:
            - configure
        - import_role: 
            name: configure-cce
          vars:
            config_item: repos
          tags:
            - configure
        - import_role: 
            name: configure-cce
          vars:
            config_item: update
          tags:
            - configure
      become: true
      become_user: "{{ cce_owner }}"
  post_tasks:
    - name: Non Root tasks
      block:
        - import_role: 
            name: post-install-webmethods
          vars:
            postinstall_force: false
            do_reboot: true
        - name: Wait for CCE ports to become open on the host
          wait_for:
            port: "{{ item }}"
            timeout: 600
          with_items:
            - 8090
            - 8091
      become: true
      tags:
        - post-install