---

### minimum params:
### cce_provisioning_inventory_hosts_pattern (type: string - the target ansible group to install the CCE template)
### cce_provisioning_inventory_hosts_property (type: string - the property to lookup to find the actual network host of an alias)
### cce_provisioning_installed_product_names (type: list - the products installed by the template so we can create the right services etc...)
### cce_provisioning_installed_product_envs_by_name (type: dictionary)
### cce_provisioning_postinstall_webmethods (type: boolean)
### cce_provisioning_postinstall_service_setup (type: boolean)
### cce_provisioning_postinstall_reboot (type: boolean)
### cce_provisioning_validation_ports (type: list)
### cce_provisioning_validation_ports_timeout (type: number)

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/base_command_central.yaml"
  tags:
    - always

- hosts: commandcentral
  become: true
  tasks:
    - name: Print the params for the webMethods post install tasks
      debug:
        msg: 
        - "Common webMethods postinstall tasks with params:"
        - "cce_provisioning_inventory_hosts_pattern = {{ cce_provisioning_inventory_hosts_pattern | default('undefined') }}"
        - "cce_provisioning_inventory_hosts_property = {{ cce_provisioning_inventory_hosts_property | default('undefined') }}"
        - "cce_provisioning_installed_product_names = {{ cce_provisioning_installed_product_names | default('undefined') }}"
        - "cce_provisioning_installed_product_instance_names = {{ cce_provisioning_installed_product_instance_names | default('undefined') }}"
        - "cce_provisioning_installed_product_envs_by_name = {{ cce_provisioning_installed_product_envs_by_name | default('undefined') }}"
        - "cce_provisioning_postinstall_webmethods = {{ cce_provisioning_postinstall_webmethods | default('undefined') }}"
        - "cce_provisioning_postinstall_service_setup = {{ cce_provisioning_postinstall_service_setup | default('undefined') }}"
        - "cce_provisioning_postinstall_reboot = {{ cce_provisioning_postinstall_reboot | default('undefined') }}"
        - "cce_provisioning_validation_ports = {{ cce_provisioning_validation_ports | default('undefined') }}"
        - "cce_provisioning_validation_ports_timeout = {{ cce_provisioning_validation_ports_timeout | default('undefined') }}"
      tags:
        - always

##stop process before installing and starting the service
- hosts: "{{ cce_provisioning_inventory_hosts_pattern }}"
  tasks:
    - name: Root tasks
      block:
        - import_role: 
            name: post-install-webmethods
          vars:
            postinstall_do_reboot: false
          when: cce_provisioning_postinstall_webmethods|bool
        - import_role: 
            name: service-webmethods
          vars:
            product_command: "create"
            product_name: "{{ cce_provisioning_installed_product_names }}"
            product_instance_name: "{{ cce_provisioning_installed_product_instance_names }}"
            force_create: false
            service_user: "{{ webmethods_user }}"
          when: cce_provisioning_postinstall_service_setup|bool
        - import_role: 
            name: service-webmethods
          vars:
            product_command: "update"
            product_name: "{{ cce_provisioning_installed_product_names }}"
            product_instance_name: "{{ cce_provisioning_installed_product_instance_names }}"
            service_env: "{{ cce_provisioning_installed_product_envs_by_name }}"
          when: cce_provisioning_postinstall_service_setup|bool
        - import_role: 
            name: command-webmethods
          vars:
            product_command: "stop"
            product_name: "{{ cce_provisioning_installed_product_names }}"
            product_instance_name: "{{ cce_provisioning_installed_product_instance_names }}"
          become: true
          become_user: "{{ webmethods_user }}"
          when: cce_provisioning_postinstall_service_setup|bool
        - import_role: 
            name: service-webmethods
          vars:
            product_command: "restart"
            product_name: "{{ cce_provisioning_installed_product_names }}"
            product_instance_name: "{{ cce_provisioning_installed_product_instance_names }}"
          when: cce_provisioning_postinstall_service_setup|bool
        - name: "Reboot the machine ONLY IF postinstall_reboot set to true"
          reboot:
            reboot_timeout: 1000
          when: cce_provisioning_postinstall_reboot is defined and cce_provisioning_postinstall_reboot == true
      become: true
  tags:
    - postinstall

#check ports
- hosts: commandcentral
  become: true
  become_user: "{{ cce_owner }}"
  tasks:
    - import_role: 
        name: check-remote-ports
      vars:
        inventory_pattern: "{{ cce_provisioning_inventory_hosts_pattern }}"
        inventory_hosts_property: "{{ cce_provisioning_inventory_hosts_property }}"
        validation_ports: "{{ cce_provisioning_validation_ports }}"
        validation_ports_timeout: "{{ cce_provisioning_validation_ports_timeout }}"
  tags:
    - postinstall