---

- import_playbook: sagenv-common-webmethods-load-vars.yaml
  tags:
    - always

- hosts: "{{ cce_provisioning_command_central_hosts | default('commandcentral') }}"
  tasks:
    - name: Root tasks
      block:
        - import_role: 
            name: prepare-cce-provisoning
          vars:
            cce_prep_type: "code"
            cce_copy_content: true
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_dir: /etc/ssh
            ssh_known_hosts_file: ssh_known_hosts
      become: true
      tags:
        - sysprep
  
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
          tags:
            - always
        - name: set facts
          set_fact:
            install_cce: false
          tags:
            - always
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_dir: "{{ ansible_env.HOME }}/.ssh"
            ssh_known_hosts_file: known_hosts
          tags:
            - always
        - import_role: 
            name: install-cce
          tags:
            - install
      become: true
      become_user: "{{ cce_owner }}"
  post_tasks:
    - name: Non Root tasks
      block:
        - import_role: 
            name: post-install-webmethods
          vars:
            postinstall_force: false
            do_reboot: true
        - name: Wait for CCE ports to become open on the host
          wait_for:
            port: "{{ item }}"
            timeout: 600
          with_items:
            - 8090
            - 8091
      become: true
      tags:
        - post-install